// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalPeAPI.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace RentalPeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202084603_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RentalPeAPI.Combo.Domain.Aggregates.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("image");

                    b.Property<int>("InstallDays")
                        .HasColumnType("int")
                        .HasColumnName("install_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plan_type");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("p_k_combos");

                    b.ToTable("combos", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Monitoring.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("IoTDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("iot_device_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reported_at");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.HasIndex("IoTDeviceId")
                        .HasDatabaseName("i_x_incidents_iot_device_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_incidents_project_id");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Monitoring.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Recipient")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("recipient");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_notifications_incident_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_notifications_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Monitoring.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int")
                        .HasColumnName("property_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_projects");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("i_x_projects_property_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_projects_user_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Monitoring.Domain.Entities.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("IoTDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("iot_device_id");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("metric_name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_readings");

                    b.HasIndex("IoTDeviceId")
                        .HasDatabaseName("i_x_readings_iot_device_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_readings_project_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("i_x_readings_timestamp");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Monitoring.Domain.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_tasks");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("i_x_tasks_assigned_to_user_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_tasks_incident_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_tasks_project_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Monitoring.Domain.Model.Aggregates.IoTDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("installation_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_iot_devices_project_id");

                    b.ToTable("iot_devices", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Payments.Domain.Model.Aggregates.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("IssueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issue_date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_invoices");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("i_x_invoices_payment_id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("RentalPeAPI.Payments.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("Installment")
                        .HasColumnType("int")
                        .HasColumnName("installment");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_payments_project_id");

                    b.HasIndex("Reference")
                        .HasDatabaseName("i_x_payments_reference");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_payments_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_payments_user_id");

                    b.HasIndex("ProjectId", "Installment")
                        .HasDatabaseName("i_x_payments_project_id_installment");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("RentalPeAPI.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("photo");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("SpaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("p_k_services");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("i_x_services_space_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Space", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AreaM2")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("area_m2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_spaces");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.User.Domain.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("cvv");

                    b.Property<string>("Expiry")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("expiry");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_payment_methods");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_payment_methods_user_id");

                    b.ToTable("user_payment_methods", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.User.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("photo");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("provider_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.providers.Domain.Model.Aggregates.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_providers");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("RentalPeAPI.subscriptions.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("Plan")
                        .HasColumnType("int")
                        .HasColumnName("plan");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_subscriptions_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_subscriptions_status");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("RentalPeAPI.Payments.Domain.Model.Aggregates.Invoice", b =>
                {
                    b.HasOne("RentalPeAPI.Payments.Domain.Model.Aggregates.Payment", null)
                        .WithOne()
                        .HasForeignKey("RentalPeAPI.Payments.Domain.Model.Aggregates.Invoice", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_invoices__payment_payment_id");
                });

            modelBuilder.Entity("RentalPeAPI.Payments.Domain.Model.Aggregates.Payment", b =>
                {
                    b.OwnsOne("RentalPeAPI.Payments.Domain.Model.ValueObjects.Money", "Money", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<int>("Currency")
                                .HasColumnType("int")
                                .HasColumnName("currency");

                            b1.HasKey("Id")
                                .HasName("p_k_payments");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_payments_payments_id");
                        });

                    b.OwnsOne("RentalPeAPI.Payments.Domain.Model.ValueObjects.PaymentMethodSummary", "Method", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Label")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("label");

                            b1.Property<string>("Last4")
                                .HasMaxLength(4)
                                .HasColumnType("varchar(4)")
                                .HasColumnName("last4");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("p_k_payments");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_payments_payments_id");
                        });

                    b.Navigation("Method")
                        .IsRequired();

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalPeAPI.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("RentalPeAPI.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("RentalPeAPI.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("RentalPeAPI.Profiles.Domain.Model.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("phone");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsMany("RentalPeAPI.Profiles.Domain.Model.Aggregates.PaymentMethod", "PaymentMethods", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Cvv")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("cvv");

                            b1.Property<string>("Expiry")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)")
                                .HasColumnName("expiry");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("number");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("type");

                            b1.Property<int>("profile_id")
                                .HasColumnType("int")
                                .HasColumnName("profile_id");

                            b1.HasKey("Id")
                                .HasName("p_k_payment_methods");

                            b1.HasIndex("profile_id")
                                .HasDatabaseName("i_x_payment_methods_profile_id");

                            b1.ToTable("payment_methods", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("profile_id")
                                .HasConstraintName("f_k_payment_methods__profile_profile_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PaymentMethods");

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Entities.Service", b =>
                {
                    b.HasOne("RentalPeAPI.Property.Domain.Aggregates.Space", "Space")
                        .WithMany("Services")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_services_space_id");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Space", b =>
                {
                    b.OwnsOne("RentalPeAPI.Property.Domain.Aggregates.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<long>("SpaceId")
                                .HasColumnType("bigint")
                                .HasColumnName("space_id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("address");

                            b1.HasKey("SpaceId")
                                .HasName("p_k_space_locations");

                            b1.ToTable("space_locations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpaceId")
                                .HasConstraintName("f_k_space_locations_spaces_space_id");
                        });

                    b.OwnsOne("RentalPeAPI.Property.Domain.Aggregates.ValueObjects.OwnerId", "OwnerId", b1 =>
                        {
                            b1.Property<long>("SpaceId")
                                .HasColumnType("bigint")
                                .HasColumnName("space_id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("owner_id");

                            b1.HasKey("SpaceId")
                                .HasName("p_k_space_owners");

                            b1.ToTable("space_owners", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpaceId")
                                .HasConstraintName("f_k_space_owners_spaces_space_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OwnerId")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalPeAPI.User.Domain.PaymentMethod", b =>
                {
                    b.HasOne("RentalPeAPI.User.Domain.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_payment_methods__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalPeAPI.subscriptions.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.OwnsOne("RentalPeAPI.subscriptions.Domain.Model.ValueObjects.SubscriptionPeriod", "Period", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("EndDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("end_date");

                            b1.Property<DateTimeOffset>("StartDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("start_date");

                            b1.HasKey("Id")
                                .HasName("p_k_subscriptions");

                            b1.ToTable("subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_subscriptions_subscriptions_id");
                        });

                    b.OwnsOne("RentalPeAPI.subscriptions.Domain.Model.ValueObjects.SubscriptionPrice", "Price", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_amount");

                            b1.HasKey("Id")
                                .HasName("p_k_subscriptions");

                            b1.ToTable("subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_subscriptions_subscriptions_id");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalPeAPI.Property.Domain.Aggregates.Space", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("RentalPeAPI.User.Domain.User", b =>
                {
                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
